//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTelecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CabDetails
    {
        public int CabId { get; set; }
        public int UserId { get; set; }
        public string CabRegNo { get; set; }
        public string CabType { get; set; }
        public int CabCapacity { get; set; }
        public string CabName { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
