//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTelecom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JourneyDetail
    {
        public int JournetId { get; set; }
        public int UserId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public double FareperKM { get; set; }
        public double TotalFare { get; set; }
        public double TotalDistance { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
